# Generated by Django 6.0.6 on 2026-06-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('G', 'Genderless'), ('U', 'Unknown')], max_length=55),
        ),
    ]
